### PR TITLE
Update maintainer list

### PR DESCRIPTION
**Pull request by nileshvd**
In my last commit (https://github.com/conda-forge/sagemaker-kernel-wrapper-feedstock/commit/da41dc5b452bd0dba382e865178e62812f837bbc) I accidentally removed my own access along with that of some of my teammmates. Restoring that access

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nileshvd** [comment]
@conda-forge/core I created this PR since I accidentally removed maintainer rights of myself, plus few more folks in my team as part of https://github.com/conda-forge/sagemaker-kernel-wrapper-feedstock/commit/da41dc5b452bd0dba382e865178e62812f837bbc

I would appreciate if you could merge this PR to restore that access.

**Comment by h-vetinari** [comment]
Actually, you should still have access, since you didn't rerender:
https://github.com/conda-forge/sagemaker-kernel-wrapper-feedstock/blob/da41dc5b452bd0dba382e865178e62812f837bbc/.github/CODEOWNERS#L1

This file (`.github/CODEOWNERS`) is what actually determines how you're able to interact with the feedstock; it gets populated from the content of `maintainers:` once you rerender, e.g. like so: @conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
So I'll let you merge this yourself. ;-)

**Comment by nileshvd** [comment]
> So I'll let you merge this yourself. ;-)

Thanks @h-vetinari for your response. Unfortunately, I am not able to merge this PR. When I look at CodeOwners file (https://github.com/conda-forge/sagemaker-kernel-wrapper-feedstock/blob/da41dc5b452bd0dba382e865178e62812f837bbc/.github/CODEOWNERS#L1), I see an error that reads:

```
Unknown owner on line 1: make sure @nileshvd exists and has write access to the repository
* @nileshvd @just4brown
```

**Comment by h-vetinari** [comment]
Do you see a merge button in this PR? If you were able to merge the previous PR, I don't see how you could have lost your rights. But ok, I'll merge for you. Make sure that anyone who wants to help maintain the feedstock actually follows the invitation to join the conda-forge organisation

**Pull request merged**
